
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[701] =
    {   0,
        0,    0,  114,  112,  110,  113,  112,   99,   99,   99,
      102,  112,   95,   93,   96,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  110,    0,
      109,  108,  111,  104,    0,  103,  102,    0,  101,   97,
       94,   98,  100,  100,  100,  100,   11,  100,  100,  100,
       15,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,

       47,   52,  100,  100,  100,  100,  100,  100,  100,  100,
       61,   62,  100,   65,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,   82,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,   11,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,   47,
      100,  100,  100,  100,  100,  100,  100,  100,  100,   65,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  111,
        0,  107,  103,    0,    0,  105,  101,    2,    1,  100,

        3,   10,   12,  100,    4,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,   39,  100,  100,
        0,  100,  100,  100,  100,  100,  100,  100,   50,   53,
      100,  100,  100,    6,    5,  100,   58,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,   77,  100,  100,  100,    7,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,   39,

      100,  100,  100,  100,  100,  100,  100,   50,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,    0,  106,
      100,  100,  100,  100,   16,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,   30,
      100,  100,   34,  100,  100,  100,  100,  100,  100,   42,
        0,    0,   43,  100,  100,  100,  100,  100,   51,  100,
       55,  100,  100,   59,  100,   63,  100,  100,  100,  100,
      100,  100,  100,   72,  100,  100,  100,  100,  100,   79,

      100,  100,  100,  100,  100,   86,  100,   88,  100,  100,
       91,   92,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,    9,  100,  100,
      100,   17,   19,  100,  100,  100,    8,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,   37,
       38,  100,   41,   43,   44,   45,  100,  100,  100,  100,

       56,  100,  100,  100,   66,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,   81,   83,  100,  100,
      100,  100,   90,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,   18,   20,   21,  100,
       23,  100,   25,  100,  100,  100,  100,   29,  100,   32,
       35,   36,  100,   46,  100,   49,  100,   57,  100,   64,
      100,  100,  100,  100,   71,  100,  100,   75,   76,  100,

      100,   84,   85,   87,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,   14,  100,
       24,  100,   26,   27,   28,  100,   40,  100,  100,   60,
      100,   68,  100,  100,  100,  100,  100,   80,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,   22,   33,   31,  100,   54,  100,  100,
      100,  100,   74,   78,   89,  100,  100,  100,  100,  100,
      100,  100,   48,   67,  100,   70,  100,  100,  100,  100,
      100,   69,   73,  100,  100,  100,  100,  100,   13,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    5,    6,
        6,    6,    7,    6,    8,    9,    6,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,    6,   12,
       13,   14,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
        1,    1,    1,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   24,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[706] =
    {   0,
        0,    0,  832,  833,   65,  833,   65,  833,  823,   61,
       63,    0,   61,  833,  817,   58,   58,   63,   81,   45,
       82,   58,  814,   84,    0,  809,  100,  101,   70,   99,
       71,   99,  115,   73,   92,  118,  114,   93,   75,  104,
      118,   99,  120,   93,  785,  115,  780,  107,  129,  106,
      133,  124,   80,  137,  144,  141,  146,  152,   77,  200,
      833,  833,    0,  194,  201,  196,  207,  211,    0,  833,
      833,  833,    0,  807,  186,  175,  807,  789,  801,  787,
        0,  208,  791,  202,  800,  786,  783,  205,  783,  780,
      785,  796,  789,  777,  781,  200,  780,  222,  218,  772,

      216,    0,  768,  778,  214,  767,  776,  785,  768,  217,
        0,    0,  217,  783,  229,  784,  239,  773,  776,  229,
      782,  769,  769,  767,  777,    0,  769,  773,  771,  763,
      769,  768,  752,  753,  739,  205,  201,  739,  722,  733,
      720,  218,  724,  215,  732,  719,  716,  226,  716,  713,
      718,  728,  721,  710,  714,  213,  713,  220,  705,  227,
      701,  711,  226,  700,  709,  717,  701,  228,  237,  715,
      238,  716,  247,  706,  708,  238,  714,  702,  702,  700,
      709,  701,  705,  703,  696,  701,  700,  685,  686,    0,
      733,  732,  281,  294,  731,  730,    0,    0,    0,  720,

        0,    0,    0,  716,    0,  700,  264,  719,  702,  699,
      706,  698,  703,  715,  273,  714,  284,  713,  708,  709,
      691,  708,  693,  707,  688,  703,  704,  699,  689,  689,
      297,  686,  659,  685,  677,  688,  687,  690,  679,    0,
      686,  687,  682,    0,    0,  681,    0,  677,  683,  673,
      677,  680,  681,  276,  680,  670,  669,  675,  667,  673,
      672,    0,  664,  670,  671,    0,  661,  280,  671,  653,
      649,  646,  285,  660,  656,  634,  630,  615,  260,  633,
      617,  614,  621,  613,  618,  629,  257,  628,  269,  627,
      622,  623,  606,  622,  608,  621,  603,  617,  618,  613,

      604,  604,  602,  594,  604,  603,  606,  596,  602,  603,
      598,  597,  594,  599,  590,  593,  596,  597,  267,  596,
      587,  586,  591,  584,  589,  588,  581,  586,  587,  578,
      267,  587,  570,  566,  563,  272,  576,  573,  613,  612,
      589,  591,  600,  597,    0,  592,  597,  588,  591,  590,
      578,  577,  591,  580,  592,  580,  591,  570,  570,    0,
      580,  576,    0,  571,  566,  577,  564,  574,  578,    0,
      566,  539,    0,  559,  562,  563,  573,  557,    0,  553,
        0,  553,  566,    0,  553,    0,  555,  551,  559,  566,
      557,  560,  555,    0,  545,  560,  548,  557,  547,    0,

      543,  552,  542,  534,  534,    0,  548,    0,  547,  546,
        0,    0,  506,  508,  516,  513,  509,  513,  505,  507,
      506,  495,  494,  507,  497,  508,  497,  507,  487,  487,
      496,  493,  488,  483,  493,  481,  490,  494,  478,  481,
      482,  491,  476,  472,  472,  484,  472,  474,  470,  477,
      484,  475,  478,  473,  464,  478,  467,  475,  466,  462,
      470,  461,  453,  453,  466,  465,  464,    0,  477,  489,
      488,    0,    0,  478,  471,  476,    0,  484,  474,  469,
      485,  484,  466,  471,  477,  467,  475,  474,  459,    0,
        0,  470,    0,  833,    0,    0,  469,  474,  454,  472,

        0,  447,  462,  456,    0,  450,  450,  455,  462,  462,
      459,  462,  461,  441,  451,  455,    0,    0,  453,  452,
      437,  433,    0,  410,  421,  420,  411,  404,  409,  416,
      407,  402,  417,  416,  399,  404,  409,  400,  407,  406,
      392,  402,  401,  406,  387,  404,  380,  394,  389,  383,
      383,  388,  394,  394,  391,  394,  393,  374,  383,  387,
      385,  384,  370,  366,  404,  398,    0,    0,    0,  390,
        0,  390,    0,  390,  396,  402,  386,    0,  402,    0,
        0,    0,  390,    0,  383,    0,  395,    0,  398,    0,
      391,  374,  393,  376,    0,  382,  392,    0,    0,  380,

      388,    0,    0,    0,  387,  355,  350,  342,  342,  342,
      348,  353,  338,  353,  342,  335,  346,  349,  342,  326,
      344,  328,  334,  343,  332,  339,  338,  343,    0,  363,
        0,  362,    0,    0,    0,  346,    0,  350,  359,    0,
      348,    0,  355,  343,  357,  348,  338,    0,  339,  304,
      319,  310,  295,  299,  307,  297,  303,  292,  305,  297,
      287,  288,  330,    0,    0,    0,  312,    0,  315,  323,
      322,  321,    0,    0,    0,  297,  280,  283,  290,  289,
      288,  299,    0,    0,  299,    0,  295,  265,  264,  249,
      272,    0,    0,  211,  216,  155,  149,  116,    0,  833,

      357,  135,  359,  363,  365
    } ;

static yyconst flex_int16_t yy_def[706] =
    {   0,
      700,    1,  700,  700,  700,  700,  701,  700,  700,  700,
      700,  702,  700,  700,  700,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  700,  701,
      700,  700,  704,  700,  700,  700,  700,  700,  705,  700,
      700,  700,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,

      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  704,
      700,  700,  700,  700,  700,  700,  705,  703,  703,  703,

      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      700,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,

      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  700,  700,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      700,  700,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,

      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  700,  703,  703,  703,  703,  703,  703,

      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,

      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  703,  703,  703,    0,

      700,  700,  700,  700,  700
    } ;

static yyconst flex_int16_t yy_nxt[900] =
    {   0,
        4,    5,    6,    5,    7,    8,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       25,   32,   33,   34,   35,   36,   37,   25,   25,   25,
        4,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   25,   53,   54,   55,
       56,   57,   58,   25,   25,   25,   59,   61,   59,   62,
       64,   66,   67,   70,   71,   74,   80,   92,   59,   65,
       59,   68,   93,   75,   82,   76,   98,  125,   83,   99,
       77,   84,   78,   79,   85,   87,   81,   86,  109,   88,

       94,  126,  115,   89,  110,  116,   65,   95,   68,   90,
       96,  101,   91,   97,  104,  106,  102,  117,  111,  127,
      141,  128,  105,  107,  129,  173,  112,  118,  113,  108,
      114,  119,  130,  120,  174,  132,  133,  135,   69,   81,
      131,  121,  134,  122,  136,  123,  137,   98,  162,  124,
      158,  138,  142,  139,  140,  143,  163,  152,  144,  147,
      167,  145,  153,  148,  146,  154,  168,  149,  160,  699,
      164,  155,  150,  102,  156,  151,  699,  157,  165,  111,
      175,  171,  176,  166,  172,  181,  112,  185,  169,  177,
      170,  178,  201,  179,  182,  186,  183,  180,  126,  184,

      187,  188,   61,   64,   62,  193,  189,  191,  191,  698,
      192,  199,   65,  202,  194,   66,   67,  195,  195,  200,
      196,  217,  207,  231,  218,   68,  208,  210,  211,  212,
      219,  228,  234,  237,  229,  250,  213,  220,  242,   65,
      243,  194,  248,  249,  697,  201,  235,  253,  238,  239,
      251,  254,   68,  257,  261,  232,  199,  255,  258,  279,
      696,  303,  262,  280,  276,  202,  282,  283,  284,  289,
      300,  306,  290,  301,  304,  285,  310,  291,  311,  313,
      314,  233,  315,  318,  292,  307,  308,  319,  322,  326,
      193,  344,  320,  323,  695,  345,  316,  262,  231,  194,

      339,  339,  390,  340,  353,  354,  356,  693,  403,  357,
      404,  391,  409,  416,  424,  425,  410,  345,  427,  451,
      428,  462,  692,  463,  694,  466,  194,  693,  452,  467,
      371,  692,  691,  690,  686,  689,  684,  683,  688,  687,
      686,  685,  684,  683,  682,  675,  674,  673,  681,  680,
      679,  678,  668,  677,  666,  665,  372,   60,   60,   60,
       60,   73,   73,  190,  664,  190,  190,  197,  197,  676,
      675,  674,  673,  672,  671,  670,  669,  668,  667,  666,
      665,  664,  663,  662,  648,  661,  660,  659,  658,  657,
      642,  656,  640,  655,  654,  637,  653,  635,  634,  633,

      652,  631,  651,  629,  650,  649,  648,  647,  646,  645,
      644,  643,  642,  641,  640,  639,  638,  637,  636,  635,
      634,  633,  632,  631,  630,  629,  628,  627,  604,  603,
      602,  626,  625,  599,  598,  624,  623,  595,  622,  621,
      620,  619,  590,  618,  588,  617,  586,  616,  584,  615,
      582,  581,  580,  614,  578,  613,  612,  611,  610,  573,
      609,  571,  608,  569,  568,  567,  607,  606,  605,  604,
      603,  602,  601,  600,  599,  598,  597,  596,  595,  594,
      593,  592,  591,  590,  589,  588,  587,  586,  585,  584,
      583,  582,  581,  580,  579,  578,  577,  576,  575,  574,

      573,  572,  571,  570,  569,  568,  567,  566,  565,  523,
      564,  563,  562,  561,  518,  517,  560,  559,  558,  557,
      556,  555,  554,  553,  552,  551,  550,  505,  549,  548,
      547,  501,  546,  545,  544,  543,  496,  495,  493,  542,
      491,  490,  541,  540,  539,  538,  537,  536,  535,  534,
      533,  532,  531,  530,  477,  529,  528,  527,  473,  472,
      526,  525,  524,  468,  523,  522,  521,  520,  519,  518,
      517,  516,  515,  514,  513,  512,  511,  510,  509,  508,
      507,  506,  505,  504,  503,  502,  501,  500,  499,  498,
      497,  496,  495,  494,  494,  493,  492,  491,  490,  489,

      488,  487,  486,  485,  484,  483,  482,  481,  480,  479,
      478,  477,  476,  475,  474,  473,  472,  471,  470,  469,
      468,  340,  340,  412,  411,  408,  465,  406,  464,  461,
      460,  400,  459,  458,  457,  456,  455,  394,  454,  453,
      450,  449,  448,  386,  447,  384,  446,  445,  381,  444,
      379,  443,  442,  441,  440,  439,  370,  438,  437,  436,
      435,  434,  433,  363,  432,  431,  360,  430,  429,  426,
      423,  422,  421,  420,  419,  418,  417,  415,  414,  413,
      412,  411,  408,  407,  406,  405,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  393,  392,  389,  388,  387,

      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  373,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  355,  352,
      351,  350,  349,  348,  347,  346,  343,  342,  341,  196,
      196,  192,  192,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  266,  329,  328,  327,  325,  324,  321,  317,
      247,  312,  245,  244,  309,  240,  305,  302,  299,  298,
      297,  296,  295,  294,  293,  288,  287,  286,  281,  278,
      205,  277,  203,  198,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  260,  259,  256,

      252,  247,  246,  245,  244,  241,  240,  236,  230,  227,
      226,  225,  224,  223,  222,  221,  216,  215,  214,  209,
      206,  205,  204,  203,  198,  161,  159,  103,  100,   72,
       63,  700,    3,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700

    } ;

static yyconst flex_int16_t yy_chk[900] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    7,    5,    7,
       10,   11,   11,   13,   13,   16,   17,   20,   59,   10,
       59,   11,   20,   16,   18,   16,   22,   34,   18,   22,
       16,   18,   16,   16,   18,   19,   17,   18,   29,   19,

       21,   34,   31,   19,   29,   31,   10,   21,   11,   19,
       21,   24,   19,   21,   27,   28,   24,   32,   30,   35,
       39,   35,   27,   28,   35,   53,   30,   32,   30,   28,
       30,   33,   36,   33,   53,   37,   37,   38,  702,   39,
       36,   33,   37,   33,   38,   33,   38,   44,   48,   33,
       44,   38,   40,   38,   38,   40,   48,   42,   40,   41,
       50,   40,   42,   41,   40,   43,   50,   41,   46,  698,
       49,   43,   41,   46,   43,   41,  697,   43,   49,   51,
       54,   52,   54,   49,   52,   55,   51,   57,   51,   54,
       51,   54,   76,   54,   56,   57,   56,   54,   55,   56,

       58,   58,   60,   64,   60,   66,   58,   65,   65,  696,
       65,   75,   64,   76,   66,   67,   67,   68,   68,   75,
       68,   88,   82,   98,   88,   67,   82,   84,   84,   84,
       88,   96,   99,  101,   96,  113,   84,   88,  105,   64,
      105,   66,  110,  110,  695,  137,   99,  115,  101,  101,
      113,  115,   67,  117,  120,   98,  136,  115,  117,  142,
      694,  158,  120,  142,  136,  137,  144,  144,  144,  148,
      156,  160,  148,  156,  158,  144,  163,  148,  163,  168,
      168,   98,  169,  171,  148,  160,  160,  171,  173,  176,
      193,  207,  171,  173,  691,  207,  169,  176,  231,  193,

      194,  194,  254,  194,  215,  215,  217,  690,  268,  217,
      268,  254,  273,  279,  287,  287,  273,  279,  289,  319,
      289,  331,  689,  331,  688,  336,  193,  687,  319,  336,
      231,  685,  682,  681,  680,  679,  678,  677,  676,  672,
      671,  670,  669,  667,  663,  662,  661,  660,  659,  658,
      657,  656,  655,  654,  653,  652,  231,  701,  701,  701,
      701,  703,  703,  704,  651,  704,  704,  705,  705,  650,
      649,  647,  646,  645,  644,  643,  641,  639,  638,  636,
      632,  630,  628,  627,  626,  625,  624,  623,  622,  621,
      620,  619,  618,  617,  616,  615,  614,  613,  612,  611,

      610,  609,  608,  607,  606,  605,  601,  600,  597,  596,
      594,  593,  592,  591,  589,  587,  585,  583,  579,  577,
      576,  575,  574,  572,  570,  566,  565,  564,  563,  562,
      561,  560,  559,  558,  557,  556,  555,  554,  553,  552,
      551,  550,  549,  548,  547,  546,  545,  544,  543,  542,
      541,  540,  539,  538,  537,  536,  535,  534,  533,  532,
      531,  530,  529,  528,  527,  526,  525,  524,  522,  521,
      520,  519,  516,  515,  514,  513,  512,  511,  510,  509,
      508,  507,  506,  504,  503,  502,  500,  499,  498,  497,
      492,  489,  488,  487,  486,  485,  484,  483,  482,  481,

      480,  479,  478,  476,  475,  474,  471,  470,  469,  467,
      466,  465,  464,  463,  462,  461,  460,  459,  458,  457,
      456,  455,  454,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  410,  409,  407,  405,  404,  403,
      402,  401,  399,  398,  397,  396,  395,  393,  392,  391,
      390,  389,  388,  387,  385,  383,  382,  380,  378,  377,
      376,  375,  374,  372,  371,  369,  368,  367,  366,  365,

      364,  362,  361,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  344,  343,  342,
      341,  340,  339,  338,  337,  335,  334,  333,  332,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  288,
      286,  285,  284,  283,  282,  281,  280,  278,  277,  276,
      275,  274,  272,  271,  270,  269,  267,  265,  264,  263,
      261,  260,  259,  258,  257,  256,  255,  253,  252,  251,

      250,  249,  248,  246,  243,  242,  241,  239,  238,  237,
      236,  235,  234,  233,  232,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  216,  214,
      213,  212,  211,  210,  209,  208,  206,  204,  200,  196,
      195,  192,  191,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  175,  174,  172,  170,
      167,  166,  165,  164,  162,  161,  159,  157,  155,  154,
      153,  152,  151,  150,  149,  147,  146,  145,  143,  141,
      140,  139,  138,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  125,  124,  123,  122,  121,  119,  118,  116,

      114,  109,  108,  107,  106,  104,  103,  100,   97,   95,
       94,   93,   92,   91,   90,   89,   87,   86,   85,   83,
       80,   79,   78,   77,   74,   47,   45,   26,   23,   15,
        9,    3,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700,  700,
      700,  700,  700,  700,  700,  700,  700,  700,  700

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scn.l"
#line 2 "scn.l"
	#include "y.tab.h"
	#include <string.h>
	const char * sql_to_lex = NULL;//全局变量，指向要分析的sql_to_lex语句
	const char * sql_to_log = NULL;//全局变量，指向要分析的sql_to_lex语句，这是用来记日志的
	int sql_len_remain = 0;//全局变量，记录字符串中还剩余的字符数
	int string_input(char* buff, int my_to_read){
		if(!sql_len_remain)
			return 0;

		if(my_to_read > sql_len_remain)
			my_to_read = sql_len_remain;

		memcpy(buff, sql_to_lex, my_to_read);

		sql_to_lex += my_to_read;
		sql_len_remain -= my_to_read;

		return my_to_read;
	}

	#define YY_INPUT( b , r , m )   (r= string_input( b , m ))

	int lineno = 1;
	void yyerror(char *s);

	/* macro to save the text and return a token */
	#define TOK(name) {/* printf("提供%s\n",yytext);yylval.strval=strdup(yytext);*/ return name; }
#line 912 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 31 "scn.l"


	/* literal keyword tokens */
#line 1098 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 701 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 833 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "scn.l"
TOK(ALL)
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "scn.l"
TOK(ADD)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "scn.l"
TOK(AND)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "scn.l"
TOK(AMMSC)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "scn.l"
TOK(AMMSC)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "scn.l"
TOK(AMMSC)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "scn.l"
TOK(AMMSC)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "scn.l"
TOK(AMMSC)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 42 "scn.l"
/*TOK(ALTER)*/ {yylval.strval.strp=yytext; yylval.strval.len=yyleng; return ALTER;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "scn.l"
TOK(ANY)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "scn.l"
TOK(AS)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "scn.l"
TOK(ASC)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "scn.l"
TOK(AUTHORIZATION)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "scn.l"
TOK(BETWEEN)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "scn.l"
TOK(BY)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "scn.l"
TOK(CHARACTER)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "scn.l"
TOK(CHECK)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "scn.l"
TOK(CHANGE)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "scn.l"
TOK(CLOSE)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "scn.l"
TOK(COLUMN)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 54 "scn.l"
TOK(COMMIT)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "scn.l"
TOK(CONTINUE)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "scn.l"
/*TOK(CREATE)*/ {yylval.strval.strp=yytext; yylval.strval.len=yyleng; return CREATE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "scn.l"
TOK(CURRENT)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "scn.l"
TOK(CURSOR)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "scn.l"
TOK(DECIMAL)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 60 "scn.l"
TOK(DECLARE)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "scn.l"
TOK(DEFAULT)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "scn.l"
/*TOK(DELETE)*/ {yylval.strval.strp=yytext; yylval.strval.len=yyleng; return DELETE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "scn.l"
TOK(DESC)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "scn.l"
TOK(DISTINCT)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "scn.l"
TOK(DOUBLE)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "scn.l"
TOK(DATABASE)/*新加的*/
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "scn.l"
/*TOK(DROP)*//*新加的*/ {yylval.strval.strp=yytext; yylval.strval.len=yyleng; return DROP;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "scn.l"
TOK(ESCAPE)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "scn.l"
TOK(EXISTS)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "scn.l"
TOK(FETCH)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 71 "scn.l"
TOK(FLOAT)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "scn.l"
TOK(FOR)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "scn.l"
TOK(FOREIGN)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "scn.l"
TOK(FOUND)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "scn.l"
TOK(FROM)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "scn.l"
TOK(GOTO)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 77 "scn.l"
TOK(GRANT)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 78 "scn.l"
TOK(GROUP)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 79 "scn.l"
TOK(HAVING)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "scn.l"
TOK(IN)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "scn.l"
TOK(INDICATOR)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "scn.l"
/*TOK(INSERT)*/ {yylval.strval.strp=yytext; yylval.strval.len=yyleng; return INSERT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "scn.l"
TOK(INTEGER)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "scn.l"
TOK(INTO)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "scn.l"
TOK(IS)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "scn.l"
TOK(KEY)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "scn.l"
TOK(LANGUAGE)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "scn.l"
TOK(LIKE)
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "scn.l"
TOK(LIMIT)
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 90 "scn.l"
TOK(MODIFY)
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 91 "scn.l"
TOK(NOT)
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 92 "scn.l"
TOK(NULLX)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 93 "scn.l"
TOK(NUMERIC)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 94 "scn.l"
TOK(OF)
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 95 "scn.l"
TOK(ON)
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 96 "scn.l"
TOK(OPEN)
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 97 "scn.l"
TOK(OPTION)
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 98 "scn.l"
TOK(OR)
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 99 "scn.l"
TOK(ORDER)
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 100 "scn.l"
TOK(PRECISION)
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 101 "scn.l"
TOK(PRIMARY)
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 102 "scn.l"
TOK(PRIVILEGES)
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 103 "scn.l"
TOK(PROCEDURE)
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 104 "scn.l"
TOK(PUBLIC)
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 105 "scn.l"
TOK(REAL)
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 106 "scn.l"
TOK(REFERENCES)
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 107 "scn.l"
TOK(ROLLBACK)
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 108 "scn.l"
TOK(SCHEMA)
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 109 "scn.l"
/*TOK(SELECT)*/ {yylval.strval.strp=yytext; yylval.strval.len=yyleng; return SELECT;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 110 "scn.l"
TOK(SET)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 111 "scn.l"
TOK(SMALLINT)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 112 "scn.l"
TOK(SOME)
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 113 "scn.l"
TOK(SQLCODE)
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 114 "scn.l"
TOK(TABLE)
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 115 "scn.l"
TOK(TO)
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 116 "scn.l"
TOK(UNION)
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 117 "scn.l"
TOK(UNIQUE)
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 118 "scn.l"
/*TOK(UPDATE)*/ {yylval.strval.strp=yytext; yylval.strval.len=yyleng; return UPDATE;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 119 "scn.l"
TOK(USER)
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 120 "scn.l"
TOK(VALUES)
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 121 "scn.l"
TOK(VIEW)
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 122 "scn.l"
TOK(WHENEVER)
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 123 "scn.l"
TOK(WHERE)
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 124 "scn.l"
TOK(WITH)
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 125 "scn.l"
TOK(WORK)
	YY_BREAK
/* punctuation */
case 93:
#line 130 "scn.l"
case 94:
#line 131 "scn.l"
case 95:
#line 132 "scn.l"
case 96:
#line 133 "scn.l"
case 97:
#line 134 "scn.l"
case 98:
YY_RULE_SETUP
#line 134 "scn.l"
TOK(COMPARISON)
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 136 "scn.l"
TOK(yytext[0])
	YY_BREAK
/* names */
case 100:
YY_RULE_SETUP
#line 140 "scn.l"
/*TOK(NAME)*/ {yylval.strval.strp=yytext; yylval.strval.len=yyleng; return NAME;}
	YY_BREAK
/* parameters */
case 101:
YY_RULE_SETUP
#line 143 "scn.l"
TOK( PARAMETER)
	YY_BREAK
/* numbers */
case 102:
#line 148 "scn.l"
case 103:
#line 149 "scn.l"
case 104:
YY_RULE_SETUP
#line 149 "scn.l"
/*TOK(INTNUM)*/ {yylval.intval=atoi(yytext); return INTNUM;}
	YY_BREAK
case 105:
#line 152 "scn.l"
case 106:
#line 153 "scn.l"
case 107:
YY_RULE_SETUP
#line 153 "scn.l"
TOK(APPROXNUM)
	YY_BREAK
/* strings */
case 108:
YY_RULE_SETUP
#line 157 "scn.l"
{
			int c = input();
			unput(c);	/* just peeking */
			if(c != '\'') return STRING; else yymore();
		}
	YY_BREAK
case 109:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 163 "scn.l"
{yyerror("Unterminated string"); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 166 "scn.l"
;	/* white space */
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 168 "scn.l"
;	/* comment */
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 171 "scn.l"
ECHO;	/* random non-SQL text */
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 173 "scn.l"
ECHO;
	YY_BREAK
#line 1737 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 701 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 701 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 700);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 173 "scn.l"


	/*当yacc探测到错误后，就调用这个函数*/
	/*正式运行的时候，将错误信息记录在错误日志里，同时将判错的sql语句也记下来，方便研究和添加语法规则*/
void yyerror(char *s){
	fprintf(stderr,"%s: %s\n", s, yytext);
	fprintf(stderr,"sql语句：%s\n", sql_to_log);
}
int yywrap(){
	return 1; 
}
int sql_lex_syn(char *my_sql){
        sql_to_lex=my_sql;
        sql_to_log=my_sql;
        sql_len_remain = strlen(sql_to_lex);
	/*分析成功，yyparse返回0，否则返回1*/
	return yyparse();
}

/*
int main()
{
        char *sql="select * from tableName limit 19;";
	sql_lex_sema(sql);
}
*/

